const lines = [
  "Mr. and Mrs. Dursley of number four, Privet Drive, were proud to say that they were perfectly normal, thank you very much.",
  "I hope you're pleased with yourselves. We could all have been killed or worse, expelled. Now if you don't mind, I'm going to bed.",
  "It does not do well to dwell on dreams and forget to live.",
  "To the well-organized mind, death is but the next great adventure.",
  "You're a little scary sometimes, you know that? Brilliant ... but scary.",
  "There will be no foolish wand-waving or silly incantations in this class. As such, I don't expect many of you to appreciate the subtle science and exact art that is potion-making. However, for those select few who possess the predisposition, I can teach you how to bewitch the mind and ensnare the senses. I can tell you how to bottle fame, brew glory, and even put a stopper in death. Then again, maybe some of you have come to Hogwarts in possession of abilities so formidable that you feel confident enough to not pay attention!",
  "It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.",
  "Yer a wizard Harry.",
  "'There are all kinds of courage,' said Dumbledore, smiling. 'It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.'",
  "The truth. It is a beautiful and terrible thing, and should therefore be treated with great caution.",
  "There are some things you can't share without ending up liking each other, and knocking out a twelve-foot mountain troll is one of them.",
  "Fear of a name only increases fear of the thing itself.",
  "It is our choices, Harry, that show what we truly are, far more than our abilities.",
  "Dobby is free.",
  "Training for the ballet, Potter?",
  "I'll be in my bedroom, making no noise and pretending I'm not there.",
  "Hearing voices no one else can hear isn't a good sign, even in the wizarding world.",
  "When in doubt, go to the library.",
  "Fawkes is a phoenix, Harry. Phoenixes burst into flame when it is time for them to die and are reborn from the ashes.",
  "Fame is a fickle friend, Harry. Celebrity is as celebrity does. Remember that.",
  "Honestly, if you were any slower, you'd be going backward.",
  "I solemnly swear I am up to no good.",
  "Honestly, am I the only person who's ever bothered to read 'Hogwarts: A History?'",
  "But you know, happiness can be found even in the darkest of times, if one only remembers to turn on the light.",
  "Don't let the muggles get you down.",
  "I want to commit the murder I was imprisoned for.",
  "Are you insane? Of course I want to leave the Dursleys! Have you got a house? When can I move in?",
  "Why, dear boy, we don't send wizards to Azkaban just for blowing up their aunts.",
  "You think the dead we loved truly ever leave us? You think that we don't recall them more clearly in times of great trouble?",
  "Mischief Managed!",
  "If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.",
  "It matters not what someone is born, but what they grow to be.",
  "We are only as strong as we are united, as weak as we are divided.",
  "Your devotion is nothing more than cowardice. You would not be here if you had anywhere else to go.",
  "Numbing the pain for a while will make it worse when you finally feel it.",
  "Anyone can speak Troll. All you have to do is point and grunt.",
  "Curiosity is not a sin... But we should exercise caution with our curiosity... yes, indeed.",
  "Twitchy little ferret, aren't you, Malfoy?",
  "Just because it's taken you three years to notice, Ron, doesn't mean no one else has spotted I'm a girl!",
  "Differences of habit and language are nothing at all if our aims are identical and our hearts are open.",
  "Give her hell from us, Peeves.' And Peeves, whom Harry had never seen take an order from a student before, swept his belled hat from his head and sprang to a salute as Fred and George wheeled about to tumultuous applause from the students below and sped out of the open front doors into the glorious sunset.",
  "I think we've outgrown full-time education... Time to test our talents in the real world, d'you recko?",
  "Harry witnessed Professor McGonagall walking right past Peeves who was determinedly loosening a crystal chandelier and could have sworn he heard her tell the poltergeist out of the corner of her mouth, 'It unscrews the other way.'",
  "I think I'll just go down and have some pudding and wait for it all to turn up — it always does in the end.",
  "Just because you have the emotional range of a teaspoon doesn't mean we all have.",
  "You can laugh, but people used to believe there were no such things as the Blibbering Humdinger or the Crumple-Horned Snorkack!",
  "I mean, it's sort of exciting, isn't it, breaking the rules?",
  "We've all got both light and dark inside us. What matters is the part we choose to act on. That's who we really are.",
  "Indifference and neglect often do much more damage than outright dislike.",
  "Youth can not know how age thinks and feels. But old men are guilty if they forget what it was to be young.",
  "Things we lose have a way of coming back to us in the end, if not always in the way we expect.",
  "Wit beyond measure is man's greatest treasure.",
  "The thing about growing up with Fred and George is that you sort of start thinking anything's possible if you've got enough nerve.",
  "And now, Harry, let us step out into the night and pursue that flighty temptress, adventure.",
  "Dumbledore says people find it far easier to forgive others for being wrong than being right.",
  "There is no need to call me sir, Professor.",
  "You're just as sane as I am.",
  "I am a wizard, not a baboon brandishing a stick.",
  "Age is foolish and forgetful when it underestimates youth.",
  "Once again, you show all the sensitivity of a blunt axe.",
  "It is the unknown we fear when we look upon death and darkness, nothing more.",
  "It is the quality of one's convictions that determines success, not the number of followers.",
  "Harry was left to ponder in silence the depths to which girls would sink to get revenge.",
  "Every human life is worth the same, and worth saving.",
  "'He must have known I'd run out on you.' 'No,' Harry corrected him. 'He must've always known you'd always want to come back.'",
  "Words are, in my not-so-humble opinion, our most inexhaustible source of magic. Capable of both inflicting injury, and remedying it.",
  "And Percy was shaking his brother, and Ron was kneeling beside them, and Fred's eyes stared without seeing, the ghost of his last laugh still etched upon his face.",
  "It is a curious thing, Harry, but perhaps those who are best suited to power are those who have never sought it. Those who, like you, have leadership thrust upon them, and take up the mantle because they must, and find to their own surprise that they wear it well.",
  "He can run faster than Severus Snape confronted with shampoo.",
  "Of course it is happening inside your head, Harry, but why on earth should that mean that it is not real?",
  "I've always wanted to use that spell.",
  "All was well.",
];

export default lines;
